Generate a scalar momentum for scalar inverse mass matrices
aesara-devs/aehmc pull request #27
Opened 2021-09-15 08:51 UTC by rlouf

The `momentum_generator` function returned by `gaussian_metric` currently returns a `vector` when `inverse_mass_matrix` is a scalar. This behavior is problematic when the logprob returned by `aeppl` takes a scalar as an input (see #26).

In this PR we make `momentum_generator` return a scalar instead, and we add a unit test. While the code "works", I think it would be cleaner if:

- `shape_tuple` returned an empty tuple for a scalar input (currently raises an exception);
- `aesara` implemented the equivalent of `np.ndim` which returns 0 for scalar.

2021-09-20 13:52 UTC, rlouf commented
This needs to be merged before #25

2021-09-20 14:07 UTC, rlouf commented
I also added a commit to circumvent `aeppl` cloning variables (mentioned in #25). We perform the grad step in an atomic variable that represents the position and then copy the actual graph of the position in the computed quantities.

2021-09-21 04:58 UTC, brandonwillard requested changes
> * `shape_tuple` returned an empty tuple for a scalar input (currently raises an exception);

It does return an empty tuple for scalars:
```python
import aesara
import aesara.tensor as at

from aesara.tensor.shape import shape_tuple


a = at.scalar()

shape_tuple(a)
# ()
```



> * `aesara` implemented the equivalent of `np.ndim` which returns 0 for scalar.

We can easily create such a function, but you can currently obtain the same result with the following:
```python
a.ndim
# 0
```

Those scalars are zero dimensional `TensorType`s, but there are also distinct `aesara.scalar.basic.Scalar` `Type`s.  I'm not sure how or why you would encounter `Scalar` types, but, even if you were, all of the above should still work:
```python
from aesara.scalar import Scalar


a_scalar = Scalar("float64")()

shape_tuple(a_scalar)
# ()

a_scalar.ndim
# 0
```

I checked the newly added scalar case in `momentum_test_cases`, and they both seem to work there, as well.  Can you provide an example of when/where those were failing?

2021-09-21 04:58 UTC, brandonwillard commented on aehmc/integrators.py
> +        new_potential_energy_grad = aesara.clone_replace(npeg, {pos: new_position})
Try the new release of AePPL; you should be able to remove this.

2021-09-21 11:07 UTC, rlouf commented
Indeed, I was passing a `float` instead of a `TensorType`. I don't have any problem when using eg `at.as_tensor(1.)` as a mass matrix. I can confirm the cloning "issue" is not a problem anymore, so I am just closing this PR.

2021-09-21 11:07 UTC, closed without merging